Traceback (most recent call last):
  File "/home/pyhome/server/lan_control/lan_control_demon.py", line 6, in <module>
    import pyaudio
ImportError: No module named 'pyaudio'
